### ISSUE TITLE
Cannot read property 'local_version' of null

### ISSUE THREAD

**Issue by AlexanderCurl** [byNeHo/CoD4x-WebAdmin#3]
I've trying to install the webadmin, but I cannot access the Admin page, it fails to check the running version.
Tried to pull from github with git clone, and tried with a released 4.0.1 as well, same error.

OS: Ubuntu 20.04.1
Node: 12.20.1
npm: 6.14.10

```
TypeError: /home/ogp_agent/CoD4x-WebAdmin/app/views/admin/home/index.pug:244
    242| 													i.zmdi.zmdi-refresh-alt
    243| 									.card-body
  > 244| 										if (results.appversion.local_version!=results.appversion.github_version)
    245| 											.alert.alert-danger
    246| 												.m-b-20
    247| 													| You are running

Cannot read property 'local_version' of null
    at eval (eval at wrap (/home/ogp_agent/CoD4x-WebAdmin/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1441:25)
    at template (eval at wrap (/home/ogp_agent/CoD4x-WebAdmin/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1931:72)
    at Object.exports.renderFile (/home/ogp_agent/CoD4x-WebAdmin/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/ogp_agent/CoD4x-WebAdmin/node_modules/pug/lib/index.js:417:21)
    at View.exports.__express [as engine] (/home/ogp_agent/CoD4x-WebAdmin/node_modules/pug/lib/index.js:464:11)
    at View.render (/home/ogp_agent/CoD4x-WebAdmin/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/ogp_agent/CoD4x-WebAdmin/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/ogp_agent/CoD4x-WebAdmin/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/ogp_agent/CoD4x-WebAdmin/node_modules/express/lib/response.js:1012:7)
    at /home/ogp_agent/CoD4x-WebAdmin/app/controllers/admin/index.js:49:8
    at tryCatcher (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise.js:673:18)
    at PropertiesPromiseArray.PromiseArray._resolve (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PropertiesPromiseArray._promiseFulfilled (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/props.js:78:14)
    at Promise._settlePromise (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/promise.js:673:18)
    at /home/ogp_agent/CoD4x-WebAdmin/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/ogp_agent/CoD4x-WebAdmin/node_modules/mongoose/lib/model.js:4863:16
    at /home/ogp_agent/CoD4x-WebAdmin/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
    at /home/ogp_agent/CoD4x-WebAdmin/node_modules/mongoose/lib/model.js:4886:21
    at /home/ogp_agent/CoD4x-WebAdmin/node_modules/mongoose/lib/query.js:4397:11
    at /home/ogp_agent/CoD4x-WebAdmin/node_modules/kareem/index.js:136:16
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by byNeHo** [comment]
Your database is not populated with default data. I will update this in future. For now change [this](https://github.com/byNeHo/CoD4x-WebAdmin/blob/master/app/seed/dbseed.js#L10) line please to this `mongoose.connect(dbURI, {useNewUrlParser:true});

I have removed this part " , useUnifiedTopology: true "

After you remove ", useUnifiedTopology: true" from that line try to run again this part

Navigate in terminal(putty) to the applications seed folder

`cd /var/www/html/app/seed`

Seed/Populate the MongoDB

`nodejs dbseed.js`

**Comment by AlexanderCurl** [comment]
Strange, I followed your installation tutorial on your forum, still got this. Anyway your suggestion worked, thanks.
