### ISSUE TITLE
mongoose node lib broken

### ISSUE THREAD

**Issue by AlexanderCurl** [byNeHo/CoD4x-WebAdmin#7]
NodeJS 17.5 broke something as far I see, now I got this.

```
/home/sanyi/Hosting/webadmin/CoD4x-WebAdmin/node_modules/mongoose/lib/cursor/QueryCursor.js:150
QueryCursor.prototype.map = function(fn) {
                          ^

TypeError: Cannot assign to read only property 'map' of object '#<QueryCursor>'
    at Object.<anonymous> (/home/sanyi/Hosting/webadmin/CoD4x-WebAdmin/node_modules/mongoose/lib/cursor/QueryCursor.js:150:27)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/sanyi/Hosting/webadmin/CoD4x-WebAdmin/node_modules/mongoose/lib/query.js:12:21)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/sanyi/Hosting/webadmin/CoD4x-WebAdmin/node_modules/mongoose/lib/index.js:27:15)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

Node.js v17.5.0
```

Workaround: Use 16.x LTS version of nodejs.

**Comment by byNeHo** [comment]
16.14.0 is right now the recommended version

**Comment by AlexanderCurl** [comment]
Yes, that's what I'm stick with, as an LTS version from now on. Just a highlight, if someone installing from scratch and want to use the 17.x branch, it will brake. Probably a good choice if we highlight in the readme as well.
