### ISSUE TITLE
getting error when run the npm start

### ISSUE THREAD

**Issue by CodeBreakerRU** [byNeHo/CoD4x-WebAdmin#8]
root@debian:~/gameserveradmin/CoD4x-WebAdmin# npm start

> cod4x-webadmin@4.4.0 start
> node ./bin/www
```

/root/gameserveradmin/CoD4x-WebAdmin/node_modules/express/lib/router/route.js:216
        throw new Error(msg);
        ^

Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (/root/gameserveradmin/CoD4x-WebAdmin/node_modules/express/lib/router/route.js:216:15)
    at proto.<computed> [as get] (/root/gameserveradmin/CoD4x-WebAdmin/node_modules/express/lib/router/index.js:521:19)
    at module.exports (/root/gameserveradmin/CoD4x-WebAdmin/app/routes/user.js:30:9)
    at Object.<anonymous> (/root/gameserveradmin/CoD4x-WebAdmin/server.js:138:29)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/root/gameserveradmin/CoD4x-WebAdmin/bin/www:7:14)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49

Node.js v18.19.0

```

**Comment by byNeHo** [comment]
Need help with installing or configuring CoD4x WebAdmin? Write [here](https://forum.cirkus-serveri.com/category/8/support)
